const config = {
	arrowParens: "always",
	bracketSpacing: true,
	embeddedLanguageFormatting: "auto",
	endOfLine: "lf",
	bracketSameLine: false,
	experimentalTernaries: true,
	htmlWhitespaceSensitivity: "css",
	jsxSingleQuote: false,
	overrides: [],
	plugins: [],
	printWidth: 80,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	semi: false,
	singleAttributePerLine: true,
	singleQuote: false,
	tabWidth: 2,
	trailingComma: "all",
	useTabs: true,
}
module.exports = config
